baseURL = "https://NeuroAI-IBS.github.io/"
languageCode = "en-us"
title = "IBS NeuroAI Group"
theme = "hugo-coder"

[params]
  author = "Neuroscience-inspired AI Research Group"
  description = "Institute for Basic Science - NeuroAI Group"
  keywords = "neuroscience,AI,machine learning,computational neuroscience,IBS"
  info = "Center for Memory and Glioscience, Institute for Basic Science"
  avatarURL = "images/logo.png"
  dateFormat = "January 2, 2006"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2024
  enableTwemoji = false
  colorScheme = "auto"
  hideColorSchemeToggle = true
  customCSS = []
  customSCSS = ["scss/custom.scss"]
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[menu.main]]
  name = "People"
  weight = 2
  url = "/people/"

[[menu.main]]
  name = "Open Positions"
  weight = 3
  url = "/opportunities/"

[[menu.main]]
  name = "Research"
  weight = 4
  url = "/research/"

[[menu.main]]
  name = "Publications"
  weight = 5
  url = "/publication/"

[[menu.main]]
  name = "Resources"
  weight = 6
  url = "/resources/"
